import { readFile, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { assertPathInsideRoot, assertSafeAssetSegments } from './security.js';

export interface IndexEntry {
  /** Manifest key: `<folder>/<slug>` or just `<slug>`. */
  key: string;
  folder: string | null;
  slug: string;
  /** Optional manifest UUID — populated from the id sidecar when available. */
  id?: string;
}

const AGENT_HEADER = [
  '// 👋 AI agents: import sprites by key, e.g.',
  '//   import { MagicPixelAssets } from "<this-dir>";',
  '//   const tree = MagicPixelAssets["items/tree"];',
  '// Keys survive folder reorganization when you use MagicPixelAssetsById instead:',
  '//   import { MagicPixelAssetsById } from "<this-dir>";',
  '//   const tree = MagicPixelAssetsById["<asset-uuid>"];',
].join('\n');

/**
 * Walk `<outDir>` and return one entry per `*.png` on disk, ordered by key.
 *
 * The CLI used to emit the typed index straight from a manifest response. That
 * coupled `index.ts` correctness to a successful network round-trip; a flaky
 * manifest call left the barrel stale while the PNGs on disk were fresh. We
 * now derive the index purely from the filesystem so it can never disagree
 * with what bundlers will see.
 */
export async function scanDiskAssets(outDir: string, cwd: string = process.cwd()): Promise<IndexEntry[]> {
  const root = resolve(cwd, outDir);
  if (!existsSync(root)) return [];

  const out: IndexEntry[] = [];
  async function walk(dir: string, folderParts: string[]): Promise<void> {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const ent of entries) {
      if (ent.isSymbolicLink()) continue;
      const full = resolve(dir, ent.name);
      try {
        assertPathInsideRoot(full, root, 'outDir');
      } catch {
        continue;
      }
      if (ent.isDirectory()) {
        // Skip the id sidecar dir or any dotted folders — never user assets.
        if (ent.name.startsWith('.')) continue;
        await walk(full, [...folderParts, ent.name]);
      } else if (ent.isFile() && ent.name.toLowerCase().endsWith('.png')) {
        const slug = ent.name.slice(0, -4);
        const folder = folderParts.length ? folderParts.join('/') : null;
        const key = folder ? `${folder}/${slug}` : slug;
        out.push({ key, folder, slug });
      }
    }
  }
  await walk(root, []);
  out.sort((a, b) => a.key.localeCompare(b.key));
  return out;
}

/**
 * Emit `<outDir>/index.ts` with a typed map of every asset key → URL, plus an
 * id-keyed map for rename-resilient imports.
 *
 *   import { MagicPixelAssets, MagicPixelAssetsById } from '@/assets/magicpixel';
 *   const a = MagicPixelAssets['player/walk'];      // breaks on rename
 *   const b = MagicPixelAssetsById['abc123…'];      // survives rename
 *
 * Vite, webpack, esbuild, Parcel, Rollup, etc. all hash these URLs at build
 * time. No runtime, no bundler config.
 */
export async function emitTypedIndex(
  outDir: string,
  entries: IndexEntry[],
  cwd: string = process.cwd(),
): Promise<string> {
  // Dedupe by key. The disk scan can't actually produce duplicates, but guard
  // anyway so a future caller passing manifest entries can't break TS compile.
  const seen = new Set<string>();
  const sorted = [...entries]
    .sort((a, b) => a.key.localeCompare(b.key))
    .filter((e) => {
      if (seen.has(e.key)) return false;
      seen.add(e.key);
      return true;
    });

  const lines: string[] = [
    '// AUTOGENERATED by @magicpixelart/cli. Do not edit.',
    '// Re-runs of `magicpixel sync` overwrite this file.',
    '//',
    AGENT_HEADER,
    '',
  ];
  // Positional identifiers (asset_0, asset_1, …) avoid collisions between
  // keys that differ only by non-alphanumeric chars (e.g. `a/b` vs `a_b`).
  const indexByKey = new Map<string, number>();
  sorted.forEach((e, i) => {
    assertSafeAssetSegments(e.folder, e.slug, e.key);
    indexByKey.set(e.key, i);
    const rel = e.folder ? `./${e.folder}/${e.slug}.png` : `./${e.slug}.png`;
    lines.push(`import asset_${i} from ${JSON.stringify(rel)};`);
  });
  lines.push('');
  lines.push('export const MagicPixelAssets = {');
  sorted.forEach((e, i) => {
    lines.push(`  ${JSON.stringify(e.key)}: asset_${i},`);
  });
  lines.push('} as const;');
  lines.push('');
  lines.push('export type MagicPixelAssetKey = keyof typeof MagicPixelAssets;');
  lines.push('');

  // Rename-resilient id map. Only populated for entries whose id we know
  // (from the sidecar written by `sync`). Entries without an id are omitted
  // rather than getting a synthetic key that could later collide.
  lines.push('export const MagicPixelAssetsById = {');
  for (const e of sorted) {
    if (typeof e.id !== 'string' || e.id.length === 0) continue;
    const i = indexByKey.get(e.key);
    if (i === undefined) continue;
    lines.push(`  ${JSON.stringify(e.id)}: asset_${i},`);
  }
  lines.push('} as const;');
  lines.push('');
  lines.push('export type MagicPixelAssetId = keyof typeof MagicPixelAssetsById;');
  lines.push('');

  const path = resolve(cwd, outDir, 'index.ts');
  const next = lines.join('\n');

  // Skip the write when contents are identical. Avoids triggering Vite/webpack
  // HMR reloads on every `--watch` poll when nothing actually changed.
  if (existsSync(path)) {
    try {
      const current = await readFile(path, 'utf8');
      if (current === next) return path;
    } catch {
      // fall through and overwrite
    }
  }
  await writeFile(path, next, 'utf8');
  return path;
}

/**
 * Ensure an `AGENTS.md` at the repo root nudges AI tools (Lovable, Cursor,
 * Claude Code, …) toward the typed index. Idempotent:
 *
 *   - If no `AGENTS.md` exists, write a short standalone one.
 *   - If one exists without our marker, append a single fenced section.
 *   - If our marker is already present, do nothing.
 */
export async function ensureAgentsDoc(outDir: string, cwd: string = process.cwd()): Promise<'created' | 'appended' | 'unchanged'> {
  const path = resolve(cwd, 'AGENTS.md');
  const importPath = guessImportPath(outDir);
  const section = renderAgentsSection(importPath);
  const marker = '<!-- magicpixel:start -->';

  if (!existsSync(path)) {
    await writeFile(path, `# AGENTS\n\n${section}\n`, 'utf8');
    return 'created';
  }
  const current = await readFile(path, 'utf8');
  if (current.includes(marker)) return 'unchanged';
  const sep = current.endsWith('\n') ? '\n' : '\n\n';
  await writeFile(path, current + sep + section + '\n', 'utf8');
  return 'appended';
}

function renderAgentsSection(importPath: string): string {
  return [
    '<!-- magicpixel:start -->',
    '## MagicPixel sprites',
    '',
    'Pixel-art assets are synced to disk by `@magicpixelart/cli`. They are plain PNGs you can `import`.',
    '',
    '```ts',
    `// 1) Import by key (matches the folder/slug shown in the MagicPixel editor):`,
    `import { MagicPixelAssets } from "${importPath}";`,
    `<img src={MagicPixelAssets["items/tree"]} />`,
    '',
    '// 2) Import by id (survives renames — pin imports that move around):',
    `import { MagicPixelAssetsById } from "${importPath}";`,
    `<img src={MagicPixelAssetsById["<asset-uuid>"]} />`,
    '```',
    '',
    'When you rename or move an asset, `magicpixel sync` prints both the old → new key',
    'and the matching `MagicPixelAssetsById[...]` hint so you can pick whichever you prefer.',
    '',
    'Keep the watcher running while you edit: `npm run magicpixel:watch`.',
    '<!-- magicpixel:end -->',
  ].join('\n');
}

function guessImportPath(outDir: string): string {
  const norm = outDir.replace(/\\/g, '/').replace(/^\.\//, '');
  // `src/...` is conventionally aliased to `@/...` in Vite/Next/etc.
  if (norm.startsWith('src/')) return `@/${norm.slice(4)}`;
  return `./${norm}`;
}
