import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { assertSafeAssetSegments } from './security.js';
import { atomicWrite } from './atomicWrite.js';
import { walkOutDirPngs } from './paths.js';
import { isStaticOutDir } from './framework.js';

export interface IndexEntry {
  /** Manifest key: `<folder>/<slug>` or just `<slug>`. */
  key: string;
  folder: string | null;
  slug: string;
  /** Optional manifest UUID — populated from the id sidecar when available. */
  id?: string;
}

const AGENT_HEADER = [
  '// 👋 AI agents: import sprites by key, e.g.',
  '//   import { MagicPixelAssets } from "<this-dir>";',
  '//   const tree = MagicPixelAssets["items/tree"];',
  '// Keys survive folder reorganization when you use MagicPixelAssetsById instead:',
  '//   import { MagicPixelAssetsById } from "<this-dir>";',
  '//   const tree = MagicPixelAssetsById["<asset-uuid>"];',
].join('\n');

/**
 * Walk `<outDir>` and return one entry per `*.png` on disk, ordered by key.
 *
 * The CLI used to emit the typed index straight from a manifest response. That
 * coupled `index.ts` correctness to a successful network round-trip; a flaky
 * manifest call left the barrel stale while the PNGs on disk were fresh. We
 * now derive the index purely from the filesystem so it can never disagree
 * with what bundlers will see.
 *
 * Delegates the actual walk to the shared `walkOutDirPngs` helper (also used
 * by sync.ts's orphan scan) so both code paths share one symlink/security
 * policy.
 */
export async function scanDiskAssets(outDir: string, cwd: string = process.cwd()): Promise<IndexEntry[]> {
  const found = await walkOutDirPngs(outDir, cwd);
  // No sort here — `emitTypedIndex` already owns the canonical key ordering.
  return found.map(({ key, folder, slug }) => ({ key, folder, slug }));
}


/**
 * Emit `<outDir>/index.ts` with a typed map of every asset key → URL, plus an
 * id-keyed map for rename-resilient imports.
 *
 *   import { MagicPixelAssets, MagicPixelAssetsById } from '@/assets/magicpixel';
 *   const a = MagicPixelAssets['player/walk'];      // breaks on rename
 *   const b = MagicPixelAssetsById['abc123…'];      // survives rename
 *
 * Vite, webpack, esbuild, Parcel, Rollup, etc. all hash these URLs at build
 * time. No runtime, no bundler config.
 */
export async function emitTypedIndex(
  outDir: string,
  entries: IndexEntry[],
  cwd: string = process.cwd(),
): Promise<string> {
  // Sort by key for stable output. The disk walker can't actually produce
  // duplicate keys (one PNG per filesystem path), but a future caller passing
  // manifest entries could — silently skip duplicates so we never emit an
  // invalid TS object literal.
  const sorted: IndexEntry[] = [];
  const seen = new Set<string>();
  for (const e of [...entries].sort((a, b) => a.key.localeCompare(b.key))) {
    if (seen.has(e.key)) continue;
    seen.add(e.key);
    sorted.push(e);
  }

  const lines: string[] = [
    '// AUTOGENERATED by @magicpixelart/cli. Do not edit.',
    '// Re-runs of `magicpixel sync` overwrite this file.',
    '//',
    AGENT_HEADER,
    '',
  ];
  // Positional identifiers (asset_0, asset_1, …) avoid collisions between
  // keys that differ only by non-alphanumeric chars (e.g. `a/b` vs `a_b`).
  const indexByKey = new Map<string, number>();
  sorted.forEach((e, i) => {
    assertSafeAssetSegments(e.folder, e.slug, e.key);
    indexByKey.set(e.key, i);
    const rel = e.folder ? `./${e.folder}/${e.slug}.png` : `./${e.slug}.png`;
    lines.push(`import asset_${i} from ${JSON.stringify(rel)};`);
  });
  lines.push('');
  lines.push('export const MagicPixelAssets = {');
  sorted.forEach((e, i) => {
    lines.push(`  ${JSON.stringify(e.key)}: asset_${i},`);
  });
  lines.push('} as const;');
  lines.push('');
  lines.push('export type MagicPixelAssetKey = keyof typeof MagicPixelAssets;');
  lines.push('');

  // Rename-resilient id map. Only populated for entries whose id we know
  // (from the sidecar written by `sync`). Entries without an id are omitted
  // rather than getting a synthetic key that could later collide.
  lines.push('export const MagicPixelAssetsById = {');
  for (const e of sorted) {
    if (typeof e.id !== 'string' || e.id.length === 0) continue;
    const i = indexByKey.get(e.key);
    if (i === undefined) continue;
    lines.push(`  ${JSON.stringify(e.id)}: asset_${i},`);
  }
  lines.push('} as const;');
  lines.push('');
  lines.push('export type MagicPixelAssetId = keyof typeof MagicPixelAssetsById;');
  lines.push('');

  const path = resolve(cwd, outDir, 'index.ts');
  const next = lines.join('\n');

  // Skip the write when contents are identical. Avoids triggering Vite/webpack
  // HMR reloads on every `--watch` poll when nothing actually changed.
  if (existsSync(path)) {
    try {
      const current = await readFile(path, 'utf8');
      if (current === next) return path;
    } catch {
      // fall through and overwrite
    }
  }
  await atomicWrite(path, next);
  return path;
}

// (atomicWrite extracted to util/atomicWrite.ts and shared across writers.)

/**
 * Ensure an `AGENTS.md` at the repo root nudges AI tools (Lovable, Cursor,
 * Claude Code, …) toward the typed index. Idempotent:
 *
 *   - If no `AGENTS.md` exists, write a short standalone one.
 *   - If one exists without our marker, append a single fenced section.
 *   - If our marker is already present, do nothing.
 */
export async function ensureAgentsDoc(outDir: string, cwd: string = process.cwd()): Promise<'created' | 'appended' | 'unchanged'> {
  const path = resolve(cwd, 'AGENTS.md');
  const section = renderAgentsSection(outDir);
  const marker = '<!-- magicpixel:start -->';

  if (!existsSync(path)) {
    await atomicWrite(path, `# AGENTS\n\n${section}\n`);
    return 'created';
  }
  const current = await readFile(path, 'utf8');
  if (current.includes(marker)) return 'unchanged';
  const sep = current.endsWith('\n') ? '\n' : '\n\n';
  await atomicWrite(path, current + sep + section + '\n');
  return 'appended';
}

/**
 * Resolve how PNGs under `outDir` are referenced by application code. Two
 * cases:
 *   - `public/...` or `static/...` (Next/Astro/Nuxt/CRA/SvelteKit) → these
 *     are served as static assets at the URL root, so the correct reference
 *     is an ABSOLUTE URL like `/magicpixel/items/tree.png`.
 *   - everything else → bundler-importable; emit an `import { … } from
 *     '@/...' | './...'` snippet that hashes the URL at build time.
 */
function resolveAssetReference(outDir: string): { mode: 'url'; baseUrl: string } | { mode: 'import'; importPath: string } {
  const norm = outDir.replace(/\\/g, '/').replace(/^\.\//, '');
  if (isStaticOutDir(outDir)) {
    // Strip the leading `public/` or `static/` — these dirs are served at the URL root.
    const baseUrl = '/' + norm.replace(/^(public|static)\//, '');
    return { mode: 'url', baseUrl };
  }
  // `src/...` is conventionally aliased to `@/...` in Vite/Next/etc.
  if (norm.startsWith('src/')) return { mode: 'import', importPath: `@/${norm.slice(4)}` };
  return { mode: 'import', importPath: `./${norm}` };
}

function renderAgentsSection(outDir: string): string {
  const ref = resolveAssetReference(outDir);
  const body =
    ref.mode === 'url'
      ? [
          `Pixel-art assets are synced to \`${outDir}\` by \`@magicpixelart/cli\`. They are`,
          `plain PNGs served at the URL root — reference them by absolute path:`,
          '',
          '```tsx',
          `<img src="${ref.baseUrl}/items/tree.png" />`,
          '```',
          '',
          `Files live on disk at \`${outDir}/<folder>/<slug>.png\` so any path you see in the`,
          'MagicPixel editor maps 1:1 to a URL.',
        ]
      : [
          'Pixel-art assets are synced to disk by `@magicpixelart/cli`. They are plain PNGs you can `import`.',
          '',
          '```ts',
          `// 1) Import by key (matches the folder/slug shown in the MagicPixel editor):`,
          `import { MagicPixelAssets } from "${ref.importPath}";`,
          `<img src={MagicPixelAssets["items/tree"]} />`,
          '',
          '// 2) Import by id (survives renames — pin imports that move around):',
          `import { MagicPixelAssetsById } from "${ref.importPath}";`,
          `<img src={MagicPixelAssetsById["<asset-uuid>"]} />`,
          '```',
          '',
          'When you rename or move an asset, `magicpixel sync` prints both the old → new key',
          'and the matching `MagicPixelAssetsById[...]` hint so you can pick whichever you prefer.',
        ];
  return [
    '<!-- magicpixel:start -->',
    '## MagicPixel sprites',
    '',
    ...body,
    '',
    'Keep the watcher running while you edit: `npm run magicpixel:watch`.',
    '<!-- magicpixel:end -->',
  ].join('\n');
}
