import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { ManifestEntry } from '../api.js';

/**
 * Emit `<outDir>/index.ts` with a typed map of every asset key → URL.
 *
 *   import { MagicPixelAssets } from '@/assets/magicpixel';
 *   const url = MagicPixelAssets['player/walk'];
 *
 * Vite, webpack, esbuild, Parcel, Rollup, etc. all hash these URLs at build
 * time. No runtime, no bundler config.
 */
export async function emitTypedIndex(
  outDir: string,
  manifest: ManifestEntry[],
  cwd: string = process.cwd(),
): Promise<string> {
  const sorted = [...manifest].sort((a, b) => a.key.localeCompare(b.key));
  const lines: string[] = [
    '// AUTOGENERATED by @magicpixel/cli. Do not edit.',
    '// Re-runs of `magicpixel sync` overwrite this file.',
    '',
  ];
  for (const e of sorted) {
    const rel = e.folder ? `./${e.folder}/${e.slug}.png` : `./${e.slug}.png`;
    const safe = JSON.stringify(rel);
    lines.push(`import asset_${slugToIdent(e.key)} from ${safe};`);
  }
  lines.push('');
  lines.push('export const MagicPixelAssets = {');
  for (const e of sorted) {
    lines.push(`  ${JSON.stringify(e.key)}: asset_${slugToIdent(e.key)},`);
  }
  lines.push('} as const;');
  lines.push('');
  lines.push('export type MagicPixelAssetKey = keyof typeof MagicPixelAssets;');
  lines.push('');

  const path = resolve(cwd, outDir, 'index.ts');
  await writeFile(path, lines.join('\n'), 'utf8');
  return path;
}

function slugToIdent(key: string): string {
  return key.replace(/[^a-zA-Z0-9]/g, '_');
}
